# 第三回 pythonの基礎(2)

記述統計と可視化の基礎が講義内容で、コーディングは基本的にpandasのことをしていたよ

### 使うcsvの作成
長いから実行したら削除している

``` python 

csv_data = """user,class

"""

myfile = open('data/user_class.csv', 'w')
myfile.write(csv_data)
myfile.close()
``` 


### 対象データ
- user_class.csv
- simple_score.csv
- user_score

### pandas

データを管理

In [1]:
import pandas as pd

### SeriesとDataFrame
SeriesとDataFrameは、pandasがデータを保持・操作するための基本構造であり、それぞれ一次元テンソルと二次元テンソルにラベル（名前やインデックス）を付与したようなデータ型。

- **Series**: 1列分のデータ（一次元）。インデックス（行ラベル）と値を持つ。
- **DataFrame**: 複数のSeriesを束ねた表形式データ（二次元）。行を管理するインデックスと、列を管理するカラム名を持つ。
- **インデックス**: 行を特定するためのラベル。デフォルトでは0から始まる連番だが、文字列や日付など任意のラベルを設定できる。
- **辞書との対応関係**:
  - Seriesは、**インデックス**をキー、**各データ**を値とした辞書とみなせる。
  - DataFrameは、**カラム名**をキー、**各列**を値とした辞書とみなせる。

In [2]:
# リスト ->シリーズ
s1 = pd.Series([0,1,2,3,4,5])
print(s1)


# 辞書
#  ->シリーズ
s2 = pd.Series({0:'foo', 1:'boo', 2:'noo'})
print(s2)

0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64
0    foo
1    boo
2    noo
dtype: str

In [3]:
df1 = pd.DataFrame(
  [[1,2,3], [4,5,6],[7,8,9]], 
  index=[10,11,12], # 行のindex名指定
  columns=['a', 'i', 'u'] # 列のカラム名指定
)

print(df1)

df2 = pd.DataFrame(
  {
    'Initial':['B','M','W'],
    'Name':['foo','huu','noo']
  },
    columns=['Name', 'Initial']
)

print(df2)

    a  i  u
10  1  2  3
11  4  5  6
12  7  8  9
  Name Initial
0  foo       B
1  huu       M
2  noo       W

### csvファイルからデータフレーム

In [4]:
df = pd.read_csv('data/simple_score.csv')
df.head(3)

    user  kokugo  shakai  sugaku  rika
0      1      30      43      51    63
1      2      39      21      49    56
2      3      29      30      23    57

### index情報の取得

In [5]:
# index information
# 開始値、修了値、インデックスの増分
print(df.index)

# 行数 len(df)でもおｋ
len(df.index)

RangeIndex(start=0, stop=5, step=1)

5

### データ参照

スライス使う

In [6]:
df[:3]

    user  kokugo  shakai  sugaku  rika
0      1      30      43      51    63
1      2      39      21      49    56
2      3      29      30      23    57

In [7]:
df[-2:]

    user  kokugo  shakai  sugaku  rika
3      4      95      87      77   100
4      5      70      71      78    67

### 列を指定してデータ抽出

In [8]:
df.columns

Index([' user', 'kokugo', 'shakai', 'sugaku', 'rika'], dtype='str')

In [9]:
df['sugaku'].head(3)

0    51
1    49
2    23
Name: sugaku, dtype: int64

### 列名をリスト形式で複数選択

In [10]:
df[[' user', 'sugaku']].head(3)

    user  sugaku
0      1      51
1      2      49
2      3      23

### ilocとloc

行と列を指定して任意の行列を抽出できる

- loc = 名前（ラベル）で探す（行名も列名も）

- iloc = 番号（ポジション）で探す（行番号も列番号も）

In [11]:
df.head(3)

    user  kokugo  shakai  sugaku  rika
0      1      30      43      51    63
1      2      39      21      49    56
2      3      29      30      23    57

In [12]:
# 2行目のデータ
df.iloc[1]

 user      2
kokugo    39
shakai    21
sugaku    49
rika      56
Name: 1, dtype: int64

In [13]:
#  2行目2列のデータだから国語
df.iloc[1,1]

np.int64(39)

In [14]:
# 上から2*3の範囲を抽出
df.iloc[0:2, 0:3]

    user  kokugo  shakai
0      1      30      43
1      2      39      21

loc

In [15]:
df.loc[1]

 user      2
kokugo    39
shakai    21
sugaku    49
rika      56
Name: 1, dtype: int64

In [16]:
df.loc[2, 'sugaku']

np.int64(23)

In [17]:
df.loc[0:1, [' user', 'sugaku']]

    user  sugaku
0      1      51
1      2      49

### 練習

データフレーム df の3から4行目,1列目と5列目のデータを iloc , loc それぞれを使って抽出してください

In [18]:
df.iloc[3:5]

    user  kokugo  shakai  sugaku  rika
3      4      95      87      77   100
4      5      70      71      78    67

In [19]:
df.loc[3:4]

    user  kokugo  shakai  sugaku  rika
3      4      95      87      77   100
4      5      70      71      78    67

### データ条件の取り出し

条件式のブール演算では` and , or , not `の代わりに` & , | , ~ `を用います。

In [20]:
# データフレームの'sugaku'列の値が50より大きく、'rika'列の値が50より大きいデータ
df[(df['sugaku'] > 50) & (df['rika'] > 50)]

    user  kokugo  shakai  sugaku  rika
0      1      30      43      51    63
3      4      95      87      77   100
4      5      70      71      78    67

In [21]:
# データフレーム df から kokugo と shakai がどちらとも50点以上でのデータを抽出
df[(df['kokugo'] > 50) & (df['shakai'] > 50)]

    user  kokugo  shakai  sugaku  rika
3      4      95      87      77   100
4      5      70      71      78    67

### 列の追加と削除
- `df['new col'] = [x,x,x,x,...]`でカラムを追加できる
- assign () メソッドで追加したい列名とその値を指定することで、新たな列を追加したデータフレームを新たに作成

- del ステートメントでデータフレームから任意の列を削除
- drop () メソッドで削除したい列名を指定、任意の列を削除したデータフレームを新たに作成
    - 列を削除する場合は、 axis引数に1を指定

In [22]:
df['eigo'] = [50,50,50,50,50]

df['ongaku'] = pd.Series([40,50,60,70,80])

df.head(3)

    user  kokugo  shakai  sugaku  rika  eigo  ongaku
0      1      30      43      51    63    50      40
1      2      39      21      49    56    50      50
2      3      29      30      23    57    50      60

In [23]:
del df['ongaku']

df

    user  kokugo  shakai  sugaku  rika  eigo
0      1      30      43      51    63    50
1      2      39      21      49    56    50
2      3      29      30      23    57    50
3      4      95      87      77   100    50
4      5      70      71      78    67    50

In [24]:
# assign()でカラム追加、元データではなく新しいdfに追加する形で原本を汚さない

df1 = df.assign(kateika = pd.Series([10,12,13,14,15]))
df1.head()

    user  kokugo  shakai  sugaku  rika  eigo  kateika
0      1      30      43      51    63    50       10
1      2      39      21      49    56    50       12
2      3      29      30      23    57    50       13
3      4      95      87      77   100    50       14
4      5      70      71      78    67    50       15

In [25]:
# drop()で指定したカラムを削除、列ならaxis=1をわすれずにね
df2 = df1.drop('eigo', axis=1)

df2

    user  kokugo  shakai  sugaku  rika  kateika
0      1      30      43      51    63       10
1      2      39      21      49    56       12
2      3      29      30      23    57       13
3      4      95      87      77   100       14
4      5      70      71      78    67       15

### 行の追加と削除
-  ~~append () 関数を用いると、元のデータフレームに新たな行を追加した新たなデータフレームを作成~~

- pandas 2.0以降は`concat([df, 追加行の内容], ignore_index=)`の形式で
- drop () メソッドを用いると、行のインデックスまたはラベルを指定することで行を削除
    - 行の時には axis 引数は省略可

In [26]:
df.head()

    user  kokugo  shakai  sugaku  rika  eigo
0      1      30      43      51    63    50
1      2      39      21      49    56    50
2      3      29      30      23    57    50
3      4      95      87      77   100    50
4      5      70      71      78    67    50

In [27]:
row = pd.DataFrame([[6,1,2,3,4,5]], columns=df.columns)

# ignore_indexで追加行の分のindexを追加
df3 = pd.concat([df, row], ignore_index=True)
df3

    user  kokugo  shakai  sugaku  rika  eigo
0      1      30      43      51    63    50
1      2      39      21      49    56    50
2      3      29      30      23    57    50
3      4      95      87      77   100    50
4      5      70      71      78    67    50
5      6       1       2       3     4     5

In [28]:
df4 = df3.drop(4)
# indexが4の行を削除
df4

    user  kokugo  shakai  sugaku  rika  eigo
0      1      30      43      51    63    50
1      2      39      21      49    56    50
2      3      29      30      23    57    50
3      4      95      87      77   100    50
5      6       1       2       3     4     5

In [29]:
row1 = pd.DataFrame([[10,9,3,4,5,5]], columns=df.columns)

df5 = pd.concat([df4, row1], ignore_index=True)
df5

    user  kokugo  shakai  sugaku  rika  eigo
0      1      30      43      51    63    50
1      2      39      21      49    56    50
2      3      29      30      23    57    50
3      4      95      87      77   100    50
4      6       1       2       3     4     5
5     10       9       3       4     5     5

### データの並び替え
- sort_index() メソッドで行(index)に基づくソート
- sort_values() メソッドで列(column)に基づくソート

↑多分列ごとのほうが使うSQLのorder by のノリ

In [30]:
# 指定した二列を下に昇順で
df6 = df.sort_values(['kokugo', 'sugaku'])
df6

    user  kokugo  shakai  sugaku  rika  eigo
2      3      29      30      23    57    50
0      1      30      43      51    63    50
1      2      39      21      49    56    50
4      5      70      71      78    67    50
3      4      95      87      77   100    50

In [31]:
# 降順なら指定する
df7 = df.sort_values(['kokugo', 'sugaku'], ascending= False)
df7

    user  kokugo  shakai  sugaku  rika  eigo
3      4      95      87      77   100    50
4      5      70      71      78    67    50
1      2      39      21      49    56    50
0      1      30      43      51    63    50
2      3      29      30      23    57    50

### データの統計量

- describe()で基本統計量

In [32]:
df.describe()

           user     kokugo     shakai     sugaku        rika  eigo
count  5.000000   5.000000   5.000000   5.000000    5.000000   5.0
mean   3.000000  52.600000  50.400000  55.600000   68.600000  50.0
std    1.581139  28.953411  27.835229  22.842942   18.119051   0.0
min    1.000000  29.000000  21.000000  23.000000   56.000000  50.0
25%    2.000000  30.000000  30.000000  49.000000   57.000000  50.0
50%    3.000000  39.000000  43.000000  51.000000   63.000000  50.0
75%    4.000000  70.000000  71.000000  77.000000   67.000000  50.0
max    5.000000  95.000000  87.000000  78.000000  100.000000  50.0

### データ連結
concat()でやる。前のやつと一緒

In [33]:
concat_row_df = pd.concat([df[:2], df[-2:]])
concat_row_df

    user  kokugo  shakai  sugaku  rika  eigo
0      1      30      43      51    63    50
1      2      39      21      49    56    50
3      4      95      87      77   100    50
4      5      70      71      78    67    50

In [34]:
# データフレームのuser列とsugaku列を縦に連結
concat_col_df = pd.concat([df.loc[ : , [' user']], df.loc[ : , ['sugaku']]])
concat_col_df

    user  sugaku
0    1.0     NaN
1    2.0     NaN
2    3.0     NaN
3    4.0     NaN
4    5.0     NaN
0    NaN    51.0
1    NaN    49.0
2    NaN    23.0
3    NaN    77.0
4    NaN    78.0

### データの結合
- merge() 関数を用いると、任意の列の値をキーとして異なるデータフレームを結合する

In [35]:
user_df = pd.DataFrame(
    {'user':[1,2,3,4,5],
        'name':['Paul', 'John', 'Ringo', 'Georgi', 'Yoko'],
        'class':['A', 'A', 'A', 'B', 'B']},
        columns=['user','name', 'class'])

user_df

   user    name class
0     1    Paul     A
1     2    John     A
2     3   Ringo     A
3     4  Georgi     B
4     5    Yoko     B

In [36]:
df = df.rename(columns={' user': 'user'})
score_df = pd.merge(df, user_df, on='user')

score_df

   user  kokugo  shakai  sugaku  rika  eigo    name class
0     1      30      43      51    63    50    Paul     A
1     2      39      21      49    56    50    John     A
2     3      29      30      23    57    50   Ringo     A
3     4      95      87      77   100    50  Georgi     B
4     5      70      71      78    67    50    Yoko     B

In [37]:
campus_df = pd.DataFrame({'user':[1,2,3,4,5], 'campus':['komaba','komaba','komaba','toho','toho']},
                         columns=['user', 'campus'])

campus_df

   user  campus
0     1  komaba
1     2  komaba
2     3  komaba
3     4    toho
4     5    toho

In [38]:
zaiseki_df = pd.merge(df, campus_df, on='user')

zaiseki_df

   user  kokugo  shakai  sugaku  rika  eigo  campus
0     1      30      43      51    63    50  komaba
1     2      39      21      49    56    50  komaba
2     3      29      30      23    57    50  komaba
3     4      95      87      77   100    50    toho
4     5      70      71      78    67    50    toho

### データのグループ

- クラスAのデータから最初の2行
- クラスBのデータから最初の2行

In [39]:
# group by
score_df.groupby('class').head(2)

   user  kokugo  shakai  sugaku  rika  eigo    name class
0     1      30      43      51    63    50    Paul     A
1     2      39      21      49    56    50    John     A
3     4      95      87      77   100    50  Georgi     B
4     5      70      71      78    67    50    Yoko     B

In [40]:
# クラスのグループごとの"sugaku"列,"rika"列の値の平均を表示
score_df.groupby('class')[['sugaku', 'rika']].mean()

       sugaku       rika
class
A        41.0  58.666667
B        77.5  83.500000

# 課題１
中央値はデータの中心傾向を観察するための記述統計の指標です。同じくデータの中心傾向
の指標である平均値と比べると、データの外れ値の影響を受けにくという特徴があります。1
変数の 個のデータを考えた時、中央値を求めるにはまず、データの値の大きさの順に並び替
えます。次に、データの数が奇数個の場合は、大きさの順に並び替えた 番目の値、
データの数が偶数個の場合は、大きさの順に並び替えた 番目と の値の平均の値、
をそれぞれデータの中央値とします。
分散はデータのばらつきを観察するための記述統計の指標です。個々のデータがデータ全体
の平均からどらぐらいばらついているかを表します。以下の通り、個々のデータの値 とデ
ータ全体の平均の値 の差の2乗和をデータ数 で割ったものが分散になります。

0から100までの整数を要素とする任意の長さのリストを引数で入力として受け取り、以下を
要素とするリストを返す avg_med_var() 関数を完成させてください。

In [41]:
def avg_med_var(input_list):
    # 初期化
    mean_value = 0
    med_value = 0
    var_value = 0
    results = [] # 結果のリスト

    input_list.sort() # リスト要素を昇順に並び替え
    mid_idx = len(input_list) // 2 # リスト中央のインデックス

    if len(input_list) % 2 ==0: # リストが偶数か奇数の中央値を計算
        med_value = (input_list[mid_idx -1] + input_list[mid_idx]) /2
    else:
        med_value = input_list[mid_idx]

    for i in range(len(input_list)):
        mse_value = (input_list[i] - mean_value)**2
    var_value += mse_value

    results.append(mean_value)
    results.append(med_value)
    results.append(var_value)
    return results

In [42]:
print(avg_med_var([1,4,3,2,5,6,8,7,9,10]))
print(avg_med_var([1,4,3,2,5,6,8,7,9,10,11]))

[0, 5.5, 100]
[0, 6, 121]

# 課題２

以下のような形式の"user_score.csv"ファイルを読み込み、データフレーム score を作成します。

- desribe() メソッドを使って、各教科ごとの記述統計を確認してください

- データフレーム score から各教科の得点がすべて平均点以上であるようなユーザの数を返す above_mean() 関数を作成してください

In [43]:
score = pd.read_csv('data/user_score.csv')
score.head(5)

   user  kokugo  shakai  sugaku  rika
0     1      30      43      51    63
1     2      39      21      49    56
2     3      29      30      23    57
3     4      95      87      77   100
4     5      70      71      78    67

In [44]:
score.describe()

             user      kokugo      shakai      sugaku        rika
count  166.000000  166.000000  166.000000  166.000000  166.000000
mean    83.500000   52.331325   39.602410   45.614458   49.885542
std     48.064193   21.835858   21.456335   24.236127   21.408130
min      1.000000    0.000000    4.000000    0.000000    9.000000
25%     42.250000   35.000000   23.000000   28.000000   31.000000
50%     83.500000   53.000000   35.000000   43.000000   49.000000
75%    124.750000   70.000000   53.750000   63.750000   65.750000
max    166.000000   96.000000   90.000000  100.000000  100.000000

### 各教科の得点がすべて平均点以上であるようなユーザの数を返す above_mean() 関数

ステップ1: ゴールを言語化する
「各教科の得点がすべて平均点以上のユーザの数を返す」

ステップ2: 必要な部品を洗い出す
- 各教科の平均点を求める → どうやって？
- 各ユーザが全教科で平均以上かを判定する → どうやって？
- 条件を満たすユーザの数を数える → どうやって？

ステップ3: pandasで部品を1つずつ試す

ステップ4: 関数にまとめる

In [45]:
def above_mean(df):
    subjects = df.drop('user', axis=1)

    means = subjects.mean()
    # 各セルが平均以上かのブール表 → 全教科Trueの行を判定 → 数える
    # .all() は全ての要素がTrueかどうかを判定するメソッドです。
    count = (subjects >= means).all(axis=1).sum()

    return count

In [46]:
above_mean(score)

np.int64(46)